### PR TITLE
GH-512 python: % -> format(); other small refactoring (part 2)

### PR DESCRIPTION
**Pull request by adrianopol**

### CODE REVIEW

**Comment by gavv** [comment]
Please exclude changes in build-3rdparty.py and compose-libs.py and rebase on fresh master.

**Comment by gavv** [comment]
Other than this, LGTM.

**Comment by gavv** [comment]
Please also rollback changes in:

* triggers.yml (accidental?)
* docfilt.py (handler in another branch)

**Review by 01SMD — COMMENTED** [review]
.

**Pull request merged**
