### PR TITLE
Splitting main() functionality

### PR DESCRIPTION
**Pull request by nolan-veed**
# Why

For https://github.com/roc-streaming/roc-toolkit/issues/656

# What

* Created Configs to hold all the configs.
* Wrote functions to setup various configs.
* Wrote functions to setup input and sender.

# Testing

WIP

### CODE REVIEW

**Comment by nolan-veed** [comment]
@gavv Can I get some thoughts on approach?

**Comment by gavv** [comment]
Thanks, will take a look in upcoming days!

I think the conflict is from [this commit](https://github.com/roc-streaming/roc-toolkit/commit/ebd0c7a2a468069f0df73364ff6dff3eb1c5c056) from [here](https://github.com/roc-streaming/roc-toolkit/pull/660).

**Comment by gavv** [comment]
Also: d873794b234b49a32a4e19ad2be37354957d90bd

**Comment by gavv** [comment]
Hi, sorry for delay. I like the approach!

A few minor comments / thoughts:

* Instead of a big `Configs` struct with all the things it maybe would be better to pass every argument explicitly.

    This way it would be clear what variables are used by what functions, and so easier to understand the flow.

* All functions are named `setup_xxx()`, but actually some of them do different things.

    Some build configs, some open devices, some configure endpoints. I suggest to reflect that in their names, again, it should make it easier to understand the flow in main().

* It would be nice if we could create all top-level objects in main().

    It seems currently the only exception is `input_source`, which we create in separate function. We could keep endpoint parsing in a function, but move construction of input source to main().

* The piece where we propagate parameters from `io_config` to `sender_config` can be extracted into a small function too.

    This way this step will be reflected in main() more explicitly and main() will be less cluttered.

**Comment by gavv** [comment]
If you'll decide to proceed with this PR, I think it's good idea to review & merge just one tool (e.g. roc_send) and then work on the rest, because we can find more pitfalls during review.

**Comment by gavv** [comment]
Hi, I've addressed this issue in 96ac193820c707a81451ac06e9e8afcbc55bbcec (a big commit that also includes this refactoring).

Thanks for inspiration!

**Pull request closed without merging**
